version: '3.4'
 
services:
  webapi:
    image: ${DOCKER_REGISTRY-}multiapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "51103:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    